presentation/iPow.Presentation.jd/Controllers/HotelController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Webdiyer.WebControls.Mvc;

namespace iPow.jd.Controllers
{
    public class HotelController : ControllerBase
    {

        /// <summary>
        /// 
        /// </summary>
        public const int picPageSize = 9;

        /// <summary>
        /// 
        /// </summary>
        public const int commPageSize = 5;

        // GET: /Hotel/
        //[OutputCache(VaryByParam = "id")]
        /// <summary>
        /// Indexes the specified id.
        /// 酒店的基本信息
        /// </summary>
        /// <param name="id">The id.</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Index(int id)
        {
            Models.HotelDetailHead hd =   Bll.HotelDetail.GetHeadHotelDetailByIdentfiyId(id);

            if (hd != null)
            {
                ViewBag.hotelid = hd.HotelId;
                ViewBag.identfiyid = hd.IdentityId;
                try
                {
                    Bll.DbSys.Db.Sys_HotelPropertyInfo.Where(e => e.ID == id).FirstOrDefault().VisitCount += 1;
                    Bll.DbSys.Db.Sys_HotelPropertyInfo.Context.SaveChanges();
                }
                catch
                {

                }
            }
            return View(hd);
        }

        //[ChildActionOnly]
        //[OutputCache(Duration = 3600)]
        /// <summary>
        /// Hotels the room.
        /// 酒店房间信息
        /// </summary>
        /// <param name="id">The id.</param>
        /// <returns></returns>
        public ActionResult HotelRoom(int id)
        {
            ViewBag.hotelid = id;
            return PartialView("HotelRoomPartial");
        }

        /// <summary>
        /// Hotels the DES.
        /// 酒店具体的一些描述
        /// </summary>
        /// <param name="id">The id.</param>
        /// <returns></returns>
        [HttpGet]
        //[OutputCache(Duration = 3600 ,VaryByParam="id")]
        public ActionResult HotelDes(int id)
        {
            Models.HotelDetailMidHotelInfo hi = Bll.HotelDetail.GetHotelDetailMidHotelInfoByIdentfiyId(id);
            return PartialView("HotelDesPartial", hi);
        }


        //下面的都没有做的

        #region 已经做了 完成于2011.7.12.16.06

        /// <summary>
        /// Hotels the comm.
        /// 首次加载酒店评论
        /// </summary>
        /// <param name="id">The id.</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult HotelComm(int id)
        {
            int total = 0;
            IQueryable<iPow.DataSys.Sys_HotelComm> hc =Bll.HotelDetail.GetHotelCommPageListByHotelId(id, 1, 5, ref total);
            PagedList<iPow.DataSys.Sys_HotelComm> hcList = null;
            if (hc != null && hc.Count() > 0)
            {
                //ViewBag.id = id;
                //ViewBag.pagesize = commPageSize;
                //ViewBag.total = total;

                hcList = new PagedList<DataSys.Sys_HotelComm>(hc, 1, commPageSize, total);
            }
            ViewBag.hotelid = id;
            return PartialView("HotelCommPartial", hcList);
        }

        /// <summary>
        /// Hotels the comm list.
        /// 酒店评论分页
        /// </summary>
        /// <param name="id">The id.</param>
        /// <param name="pi">The pi.</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult HotelCommList(int id, int? pi)
        {
            int total = 0;
            int pageIdex = pi == null ? 1 : (int)pi;
            IQueryable<iPow.DataSys.Sys_HotelComm> hc = Bll.HotelDetail.GetHotelCommPageListByHotelId(id, pageIdex, 5, ref total);
            PagedList<iPow.DataSys.Sys_HotelComm> hcList = null;
            if (hc != null && hc.Count() > 0)
            {
                //ViewBag.id = id;
                //ViewBag.pagesize = commPageSize;
                //ViewBag.total = total;
                hcList = new PagedList<DataSys.Sys_HotelComm>(hc, pageIdex, commPageSize, total);
            }
            ViewBag.hotelid = id;
            return PartialView("HotelCommListPartial", hcList);
        }

        /// <summary>
        /// Adds the hotel comm.
        /// 添加酒店评论
        /// </summary>
        /// <param name="f">The f.</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AddHotelComm(FormCollection f)
        {
            if (f != null)
            {
                try
                {
                    iPow.DataSys.Sys_HotelComm hc = new DataSys.Sys_HotelComm();

                    #region init

                    hc.AddTime = System.DateTime.Now;
                    hc.CommID = Bll.DbSys.Db.Sys_HotelComm.Max(e => e.CommID) + 1;
                    if (f["Content"] != null)
                    {
                        hc.Content = f["Content"];
                    }
                    if (f["HotelID"] != null)
                    {
                        hc.HotelID = int.Parse(f["HotelID"].ToString());
                    }
                    hc.Ip = iPow.function.StringHelper.GetRealIP();
                    if (hc.Ip == "::1")
                    {
                        hc.Ip = "127.0.0.1";
                    }
                    if (f["Sroce"] != null)
                    {
                        hc.Point = int.Parse(f["Sroce"].ToString());
                    }
                    hc.UserID = 0;
                    if (f["UserName"] != null)
                    {
                        hc.UserName = f["UserName"].ToString();
                    }
                    #endregion

                   Bll.DbSys.Db.AddToSys_HotelComm(hc);
                    if (Bll.DbSys.Db.Sys_HotelComm.Context.SaveChanges() > 0)
                    {
                        var hotelInfo = Bll.DbSys.Db.Sys_HotelPropertyInfo.Where(e => e.ID == hc.HotelID).FirstOrDefault() ;
                        hotelInfo.CommCount += 1;
                        Bll.DbSys.Db.Sys_HotelPropertyInfo.Context.SaveChanges();

                        int total = 0;
                        IQueryable<iPow.DataSys.Sys_HotelComm> hcs = Bll.HotelDetail.GetHotelCommPageListByHotelId(hc.HotelID, 1, 5, ref total);
                        PagedList<iPow.DataSys.Sys_HotelComm> hcList = null;
                        if (hcs != null && hcs.Count() > 0)
                        {
                            hcList = new PagedList<DataSys.Sys_HotelComm>(hcs, 1, commPageSize, total);
                        }
                        ViewBag.hotelid = hc.HotelID;
                        return PartialView("HotelCommListPartial", hcList);
                    }
                }
                catch
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }
            }
            return Json("", JsonRequestBehavior.AllowGet);
        }
        #endregion

        /// <summary>
        /// Hotels the pic.
        /// 酒店图片
        /// 首次加载
        /// </summary>
        /// <param name="id">The id.</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult HotelPic(int id)
        {
            IQueryable<iPow.DataSys.Sys_HotelPic> hp = null;
            PagedList<iPow.DataSys.Sys_HotelPic> hpList = null;
            int total = 0;
            hp = Bll.HotelDetail.GetHotelPicPageListByHotelId(id, 1, picPageSize, ref total);
            if (hp != null && hp.Count() > 0)
            {
                hpList = new PagedList<iPow.DataSys.Sys_HotelPic>(hp, 1, picPageSize, total);
            }
            return PartialView("HotelPicPartial", hpList);
        }

        /// <summary>
        /// Hotels the pic list.
        /// 酒店图片分页
        /// </summary>
        /// <param name="id">The id.</param>
        /// <param name="pi">Index of the page.</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult HotelPicList(int id, int? pi)
        {
            //不用写单独的东西出来了，直接用数据库里面的就是了 ，数据量也不大
            //随机9张
            //可能会改进那种分页的那种
            IQueryable<iPow.DataSys.Sys_HotelPic> hp = null;
            PagedList<iPow.DataSys.Sys_HotelPic> hpList = null;
            int pageIndex = (pi == null ? 1 : (int)pi);
            int total = 0;
            hp = Bll.HotelDetail.GetHotelPicPageListByHotelId(id, pageIndex, picPageSize, ref total);
            if (hp != null && hp.Count() > 0)
            {
                hpList = new PagedList<iPow.DataSys.Sys_HotelPic>(hp, pageIndex, picPageSize, total);
            }
            return PartialView("HotelPicListPartial", hpList);
        }

        //2011.7.10.17.42完成
        /// <summary>
        /// Adds the hotel live in.
        /// 酒店的我住过
        /// </summary>
        /// <param name="id">The id.</param>
        /// <returns></returns>
        [HttpGet]
        [NoCache]
        public JsonResult AddHotelLiveIn(int id)
        {
            bool tar = false;
            int? temp = 0;
            try
            {
                iPow.DataSys.Sys_HotelPropertyInfo hi = Bll.DbSys.Db.Sys_HotelPropertyInfo.Where(e => e.ID == id).FirstOrDefault();
                if (hi != null)
                {
                    hi.LiveInCount += 1;
                    temp = hi.LiveInCount;
                }
             Bll.DbSys.Db.Sys_HotelPropertyInfo.Context.SaveChanges();
                tar = true;
            }
            catch
            {

            }
            return Json(new { success = tar, livein = temp }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Hotels the traffic.
        /// 交通
        /// </summary>
        /// <param name="id">The id.</param>
        /// <returns></returns>
        //[HttpGet]
        [ChildActionOnly]
        public ActionResult HotelTraffic(int id)
        {
            ViewBag.hotelid = id;
            Models.HotelTraffic ht =Bll.HotelDetail.GetHotelTrafficByHotelId(id);
            return PartialView("HotelTrafficPartial", ht);
        }
    }

   
}

presentation/iPow.Presentation.jd/Controllers/RightTodayLowPriceHotHotelController.cs
using System.Web.Mvc;

namespace iPow.jd.Controllers
{
    public class RightTodayLowPriceHotHotelController : ControllerBase
    {
        //
        // GET: /TodayLowPrice/
        [ChildActionOnly]
        [OutputCache(Duration = 3600)]
        public ActionResult GetTodayLowPrice()
        {
            return PartialView("RightTodayLowPrice");
        }

        [ChildActionOnly]
        [OutputCache(Duration = 3600)]
        public ActionResult GetHotHotel()
        {
            return PartialView("RightHotHotelPartial");
        }
    }
}

presentation/iPow.Presentation.jd/Views/Hotel/HotelCommListPartial.cshtml
@using Webdiyer.WebControls.Mvc
@model Webdiyer.WebControls.Mvc.PagedList<iPow.DataSys.Sys_HotelComm>
<div class="commBody" id="CommonList">
    @{
        if (Model != null && Model.Count() > 0)
        {
            foreach (var item in Model)
            {
                var userId = "user" + item.UserID.ToString();
                var ips = item.Ip.Split('.');
                var ip = ips[0] + "." + ips[1] + ".*.*";
                var contentId = "commContent" + item.UserID.ToString();
        <p class="over">
            <img src="/Content/images/face/face1.jpg" width="45" height="45" class="face" />
            <span class="spanUser" id='@(userId)'><b>iPow@(item.UserName)</b> ip：@(ip)</span>
            @* <span class="spanScore">@item.Point</span>*@ <span class="content" id="@(contentId)">@(item.Content)</span>
            <span class="control">发表于：@(item.AddTime.ToString())&nbsp;&nbsp;&nbsp;&nbsp; <a href="javascript:;"
                onclick="showCommReply('')" style="display: none">引用回复</a>&nbsp;</span>
        </p>
            }
        }
        else
        {
        <p>
            暂时还没有评论的，评论一个吧……
        </p>
        }
   
    }
</div>
<div class="" style="text-align: right;" id="PageList">
    @{
        @Html.AjaxPager(Model.TotalPageCount, Model.CurrentPageIndex,
        "HotelCommList",
        "Hotel",
        "hotelcommlist",
         new PagerOptions() { PageIndexParameterName = "pi", LastPageText = "尾页", FirstPageText = "首页", PrevPageText = "上一页", NextPageText = "下一页", CurrentPagerItemWrapperFormatString = "<span class=\"current\">{0}</span>" },
         new { id = ViewBag.hotelid },
        new AjaxOptions()
        {
            UpdateTargetId = "updateCommList",
            OnBegin = "",
            OnComplete = ""
        },
            null)
    }
</div>

presentation/iPow.Presentation.jd/Views/Hotel/HotelCommPartial.cshtml
@using Webdiyer.WebControls.Mvc
@model Webdiyer.WebControls.Mvc.PagedList<iPow.DataSys.Sys_HotelComm>
<script src="@Url.Content("~/Scripts/jquery.form.js")" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#fromAddComm').submit(function () {
            var options = {
                target: '#updateCommList',   // target element(s) to be updated with server response 
                beforeSubmit: showRequest,  // pre-submit callback 
                success: showResponse,  // post-submit callback 
                type: 'POST',
                url: '/hotel/addhotelcomm/1',
                data: null,
                dataType: null,
                timeout: 6000
            };
            $(this).ajaxSubmit(options);
            return false;
        });
    });

    function showRequest(formData, jqForm, options) {
        var queryString = $.param(formData);
        return checkedCommForm();
    }

    function checkedCommForm() {
        if ($('#UserName').val() == '') {
            $('#UserName').focus();
            alert('写个称呼吧');
            return false;
        }
        if ($('#Content').val() == '') {
            $('#Content').focus();
            alert('内容不能为空哦');
            return false;
        }
        return true;
    }

    function showResponse(responseText, statusText, xhr, $form) {
        //alert(responseText); //返回结果
        //是否成功
        if (statusText == 'success') {
            alert('评论成功');
        }
        else {
            alert('麻烦你再试一下看看');
        }

    } 
</script>
<!--用户评论开始-->
@*<div class="tabcontainerhide" id="hotelInfo4">*@
<div class="infoGuid">
    <img src="/images/ico01.gif" width="16" height="16" align="absmiddle" />用户评论 ///
</div>
<div class="infoContainer">
    <div id="updateCommList">
        <div class="commBody" id="CommonList">
            @{
                if (Model != null && Model.Count() > 0)
                {
                    foreach (var item in Model)
                    {
                        var userId = "user" + item.UserID.ToString();
                        var ips = item.Ip.Split('.');
                        var ip = ips[0] + "." + ips[1] + ".*.*";
                        var contentId = "commContent" + item.UserID.ToString();
                <p class="over">
                    <img src="/Content/images/face/face1.jpg" width="45" height="45" class="face" />
                    <span class="spanUser" id='@(userId)'><b>iPow@(item.UserName)</b> ip：@(ip)</span>
                    @* <span class="spanScore">@item.Point</span>*@ <span class="content" id="@(contentId)">@(item.Content)</span>
                    <span class="control">发表于：@(item.AddTime.ToString())&nbsp;&nbsp;&nbsp;&nbsp; <a href="javascript:;"
                        onclick="showCommReply('')" style="display: none">引用回复</a>&nbsp;</span>
                </p>
                    }
                }
                else
                {
                <p>
                    暂时还没有评论的，评论一个吧……
                </p>
                }
            }
        </div>
        <div class="" style="text-align: right;" id="PageList">
            @{
                @Html.AjaxPager(Model, "HotelCommList", "Hotel",
                     new PagerOptions() { PageIndexParameterName = "pi", LastPageText = "尾页", FirstPageText = "首页", PrevPageText = "上一页", NextPageText = "下一页", CurrentPagerItemWrapperFormatString = "<span class=\"current\">{0}</span>" },
                                       new AjaxOptions() { UpdateTargetId = "updateCommList", OnBegin = "", OnComplete = "" });
            }
        </div>
    </div>
    <div class="commBody">
        <div class="commTitle" style="font-size: 14px; font-weight: bold;">
            添加评论
        </div>
        <form id="fromAddComm">
        <div style="display: none">
            <input  value="@(ViewBag.hotelid == null ? "" : ViewBag.hotelid)"  id="HotelID" name = "HotelID" />
            <input value="" id="UserId" name="UserId" />
        </div>
        <div class="commTitle">
            <input class="input3" size="20" value="游客" name="UserName" id="UserName" />顺便打个分
            <input name="Sroce" type="radio" id="Sroce" value="5" />
            <img height="11" src="/images/start.gif" width="12" />
            <img height="11" src="/images/start.gif" width="12" />
            <img height="11" src="/images/start.gif" width="12" />
            <img height="11" src="/images/start.gif" width="12" />
            <img height="11" src="/images/start.gif" width="12" />
            <input name="Sroce" type="radio" id="Sroce" value="4" />
            <img height="11" src="/images/start.gif" width="12" />
            <img height="11" src="/images/start.gif" width="12" />
            <img height="11" src="/images/start.gif" width="12" />
            <img height="11" src="/images/start.gif" width="12" />
            <input name="Sroce" type="radio" id="Sroce" value="3" />
            <img height="11" src="/images/start.gif" width="12" />
            <img height="11" src="/images/start.gif" width="12" />
            <img height="11" src="/images/start.gif" width="12" />
            <input name="Sroce" type="radio" id="Sroce" value="2" />
            <img height="11" src="/images/start.gif" width="12" />
            <img height="11" src="/images/start.gif" width="12" />
            <input name="Sroce" type="radio" id="Sroce" value="1" />
            <img height="11" src="/images/start.gif" width="12" />
        </div>
        <div class="commTitle">
            <textarea class="input3" id="Content" name="Content" rows="6" cols="70"></textarea>
        </div>
        <div class="commTitle">
            <input type="submit" style="background: url('/images/btn_Submit.gif') no-repeat scroll 0 0 transparent;
                width: 50px; height: 20px; cursor: pointer;" value="" id="btnAddHotelComm" />
            请大伙遵纪守法并注意语言文明
        </div>
        </form>
    </div>
    <div class="clear">
    </div>
</div>
@*</div>*@
<!--用户评论结束-->

presentation/iPow.Presentation.jd/Views/Hotel/HotelDesPartial.cshtml
@model  iPow.jd.Models.HotelDetailMidHotelInfo

<!--酒店简介开始-->
<div class="infoGuid">
    <img src="/images/ico01.gif" width="16" height="16" align="absmiddle" />酒店简介 ///
</div>
<div class="infoContainer">
    <p>
        @{
            if (Model != null)
            { 
            <span class="font14">@(Model.HotelName)简介：</span> 
            <span id="desc1">
                @(Model.HotelDes)
            </span>    
            }
        }
    </p>
</div>
<!--酒店简介结束-->
<!--地理位置开始-->
<div class="infoGuid">
    <img src="/images/ico01.gif" width="16" height="16" align="absmiddle" />地理位置 ///
</div>
<div class="infoContainer">
    <p>
        @{
            if (Model != null)
            {
            @(Model.HotelAddress)
            }
        }
    </p>
</div>
<!--地理位置结束-->
<!--服务设施开始-->
<div class="infoGuid">
    <img src="/images/ico01.gif" width="16" height="16" align="absmiddle" />服务设施 ///
</div>
<div class="infoContainer">
    <p>
        @{
            if (Model != null)
            {
            @(Model.HotelFac)
            }
        }
    </p>
</div>
<!--服务设施结束-->
<!--餐饮设施开始-->
<div class="infoGuid">
    <img src="/images/ico01.gif" width="16" height="16" align="absmiddle" />餐饮设施 ///
</div>
<div class="infoContainer">
    <p>
        @{
            if (Model != null)
            {
            @(Model.HotelDining)
            }
        }
    </p>
</div>
<!--餐饮设施结束-->
<!--娱乐设施开始-->
<div class="infoGuid">
    <img src="/images/ico01.gif" width="16" height="16" align="absmiddle" />娱乐设施 ///
</div>
<div class="infoContainer">
    <p>
        @{
            if (Model != null)
            {
            @(Model.HotelRec)
            }
        }
    </p>
</div>
<!--娱乐设施结束-->

presentation/iPow.Presentation.jd/Views/Hotel/HotelPicListPartial.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<iPow.DataSys.Sys_HotelPic>
@{
    if (Model != null && Model.Count() > 0)
    {
        foreach (var item in Model)
        {
            if (!string.IsNullOrEmpty(item.PicPath) && !string.IsNullOrEmpty(item.PicName))
            { 
    <a href="@(item.PicPath + item.PicName)" class="imgList"
                target="_blank">
        <img src="@(item.PicPath + item.PicName)" alt="" /></a>
            }
        }
    }
}
<p>
    @{
        @Html.AjaxPager(Model, "HotelPicList", "Hotel",
                new PagerOptions()
                {
                    PageIndexParameterName = "pi",
                    LastPageText = "尾页",
                    FirstPageText = "首页",
                    PrevPageText = "上一页",
                    NextPageText = "下一页",
                    CurrentPagerItemWrapperFormatString = "<span class=\"current\">{0}</span>",
                    CssClass = "Pagecon"
                },
                new AjaxOptions()
                {
                    UpdateTargetId = "updatePic",
                    OnBegin = "",
                    OnComplete = ""
                })
    }
</p>

presentation/iPow.Presentation.jd/Views/Hotel/HotelPicPartial.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<iPow.DataSys.Sys_HotelPic>
<!--酒店图片开始-->
@*<div class="tabcontainerhide" id="hotelInfo3">*@
<div class="infoGuid">
    <img src="/images/ico01.gif" width="16" height="16" align="absmiddle" />酒店图片 ///
</div>
<div class="infoContainer" style="padding-bottom: 5px;" id="updatePic">
    @{
        if (Model != null && Model.Count() > 0)
        {
            foreach (var item in Model)
            {
                if (!string.IsNullOrEmpty(item.PicPath) && !string.IsNullOrEmpty(item.PicName))
                { 
        <a href="@(item.PicPath + item.PicName)" class="imgList"
                target="_blank">
            <img src="@(item.PicPath + item.PicName)" alt="" /></a>
                }
            }
        }
    }
    <p>
        @{
            @Html.AjaxPager(Model, "HotelPicList", "Hotel",
                new PagerOptions()
                {
                    PageIndexParameterName = "pi",
                    LastPageText = "尾页",
                    FirstPageText = "首页",
                    PrevPageText = "上一页",
                    NextPageText = "下一页",
                    CurrentPagerItemWrapperFormatString = "<span class=\"current\">{0}</span>",
                    CssClass = "Pagecon"
                },
                new AjaxOptions()
                {
                    UpdateTargetId = "updatePic",
                    OnBegin = "",
                    OnComplete = ""
                })
        }
    </p>
</div>

presentation/iPow.Presentation.jd/Views/Hotel/Index.cshtml
@model iPow.jd.Models.HotelDetailHead
@{
    ViewBag.Title = ((Model != null && !string.IsNullOrEmpty(Model.HotelName)) ? Model.HotelName + "_":string.Empty )  + "酒店预定_";
}
<link type="text/css" rel="stylesheet" href=" @Url.Content("~/Content/ad.css")  " />
<link type="text/css" rel="stylesheet" href="@Url.Content("~/Content/top.css")" />
<link type="text/css" rel="stylesheet" href="@Url.Content("~/Content/hotel.css")" />
<script src="@Url.Content("~/Scripts/common.js")" type="text/javascript"></script>

@Html.Partial("HeadDiscountPartial")
<div class="mainContainer">
    <!--左侧内容开始-->
    <div class="mainContainerLeft">
        @{
            if (Model != null)
            { 
            <div class="guidInfo">
                <div class="guidTop">
                </div>
                <div class="guidBottom">
                    <div class="guidBottomLeft">
                        <div class="guidBottomLeft1">
                            <span class="spanTitle">
                                <h1>
                                    @(Model.HotelName == null ? "暂时还没有名字" : Model.HotelName)</h1>
                            </span><span class="spanClass">
                                <h4>
                                    @( Model.ClassName == null ? "暂时没有分类" : Model.ClassName)
                                </h4>
                            </span>
                        </div>
                        <div class="guidBottomLeft1">
                            <p>
                                地址：@(Model.Address == null ? "我们暂时还没有酒店地址，不过你可以google一下地址" : Model.Address)
                                <br />
                                电话：@(Model.Phone == null ? "暂时还没有联系电话" : Model.Phone)
                            </p>
                        </div>
                    </div>
                    <div class="guidBottomRight">
                        <div class="guidGo">
                            <div class="guidGoShow">
                                <span style="font-size: 14px; font-weight: bold;" id="LiveInCount">@(Model.LiveIn == null ? 0 : Model.LiveIn)</span>
                                <br/>
                                人住过
                            </div>
                            <div class="guidGoShowBanner">
                                <a href="javascript:void(0);" onclick="UpdateHotelLiveIn('/hotellivein/',@(ViewBag.identfiyid),'LiveInCount')">
                                    我住过</a>
                            </div>
                        </div>
                        <div class="guidGo1">
                            <div class="guidGoShow">
                                <span style="font-size: 14px; font-weight: bold;" id="CommCount">@( Model.CommCount == null ? 0 : Model.CommCount)</span>
                                <br/>
                                条评论
                            </div>
                            <div class="guidGoShowBanner">
                                <a href="javascript:" id = "NeedComm">我要评论</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tabmenu" id="hotelinfo_menu">
                <ul>
                    <li id = "menuId1" class="tabcurrent" onclick ="GetDetailMidHotelInfo('/hotelroomprice/@(ViewBag.hotelid)','','hotelInfo' , 1)">
                        房型报价 </li>
                    <li  id = "menuId2"   onclick = "GetDetailMidHotelInfo('/hoteldes/@(ViewBag.identfiyid)','','hotelInfo' , 2)">
                        酒店信息 </li>
                    <li  id = "menuId3"  onclick = "GetDetailMidHotelInfo('/hotelpic/@(ViewBag.hotelid)','','hotelInfo', 3)">
                        酒店图片 </li>
                    <li  id = "menuId4"  onclick = "GetDetailMidHotelInfo('/hotelcomm/@(ViewBag.identfiyid)','','hotelInfo',4)">
                        用户评论 </li>
                </ul>
            </div>
            <script type ="text/javascript">
                $('#NeedComm').click(function () {
                    GetDetailMidHotelInfo('/hotelcomm/@(ViewBag.identfiyid)', '', 'hotelInfo', 4);
                });

</script>
            }
        }
        <div class="guidInfo">
            <div style="float: left; width: 100%; padding-bottom: 10px;" id="hotelInfo">
                @Html.Action("HotelRoom", "Hotel", new { id = (ViewBag.hotelid == null ? 0 : ViewBag.hotelid) })
            </div>
            <div style="float: left; width: 100%; height: 20px;">
            </div>
        </div>
        <div style="float: left; width: 100%; height: 10px;">
        </div>
        <div class="guidInfo">
            @Html.Action("HotelTraffic", "Hotel", new { id = ViewBag.hotelid })
        </div>
    </div>
    <!--左侧内容结束-->
    <!--右侧内容开始-->
    <div class="mainContainerRight">
        <div class="rightGuid1">
            <h3>
                今日低价</h3>
        </div>
        <div class="rightContainer1">
            <ul>
                @Html.Action("GetTodayLowPrice", "RightTodayLowPriceHotHotel")
            </ul>
        </div>
        <div class="rightGuid2">
            <h3>
                人气酒店排行榜</h3>
        </div>
        <div class="rightContainer2">
            <ul>
                @Html.Action("GetHotHotel", "RightTodayLowPriceHotHotel")
            </ul>
        </div>
    </div>
    <!--右侧内容结束-->
    <div class="clear">
    </div>
</div>